from city import City
from connection import Connection
from game import Game
from path import Path

game = Game()

# create cities:
game.all_cities.append(City("Fairbanks", "a", "1"))
game.all_cities.append(City("Inuvik", "a", "1"))

game.all_cities.append(City("Nuuk", "c", "1"))

game.all_cities.append(City("Reykjavik", "d", "1"))

game.all_cities.append(City("Barentsburg", "e", "1"))
game.all_cities.append(City("Trondheim", "e", "1"))
game.all_cities.append(City("Oslo", "e", "1"))
game.all_cities.append(City("Stockholm", "e", "1"))

game.all_cities.append(City("Helsinki", "f", "1"))
game.all_cities.append(City("Murmansk", "f", "1"))
game.all_cities.append(City("StPetersburg", "f", "1"))
game.all_cities.append(City("Archangelsk", "f", "1"))

game.all_cities.append(City("Norilsk", "h", "1"))

game.all_cities.append(City("Jakutsk", "j", "1"))

game.all_cities.append(City("Juneau", "a", "2"))
game.all_cities.append(City("Vancouver", "a", "2"))
game.all_cities.append(City("Portland", "a", "2"))
game.all_cities.append(City("SaltLakeCity", "a", "2"))
game.all_cities.append(City("SanFrancisco", "a", "2"))

game.all_cities.append(City("Churchill", "b", "2"))
game.all_cities.append(City("Edmonton", "b", "2"))
game.all_cities.append(City("Winnipeg", "b", "2"))
game.all_cities.append(City("Toronto", "b", "2"))
game.all_cities.append(City("Chicago", "b", "2", True))
game.all_cities.append(City("StLouis", "b", "2"))
game.all_cities.append(City("Washington", "b", "2"))

game.all_cities.append(City("Montreal", "c", "2"))
game.all_cities.append(City("StJohns", "c", "2"))
game.all_cities.append(City("NewYork", "c", "2"))

game.all_cities.append(City("Dublin", "d", "2"))

game.all_cities.append(City("London", "e", "2"))
game.all_cities.append(City("Kopenhagen", "e", "2"))
game.all_cities.append(City("Amsterdam", "e", "2"))
game.all_cities.append(City("Berlin", "e", "2", True))
game.all_cities.append(City("Brussel", "e", "2"))
game.all_cities.append(City("Warschau", "e", "2"))
game.all_cities.append(City("Prag", "e", "2"))
game.all_cities.append(City("Paris", "e", "2"))
game.all_cities.append(City("Bern", "e", "2"))
game.all_cities.append(City("Wien", "e", "2"))
game.all_cities.append(City("Belgrad", "e", "2"))
game.all_cities.append(City("Rom", "e", "2"))
game.all_cities.append(City("Madrid", "e", "2"))
game.all_cities.append(City("Budapest", "e", "2"))

game.all_cities.append(City("Riga", "f", "2"))
game.all_cities.append(City("Moskau", "f", "2"))
game.all_cities.append(City("Kiew", "f", "2"))
game.all_cities.append(City("Wolgograd", "f", "2"))
game.all_cities.append(City("Bukarest", "f", "2"))
game.all_cities.append(City("Sofia", "f", "2"))
game.all_cities.append(City("Tiflis", "f", "2"))
game.all_cities.append(City("Baku", "f", "2"))

game.all_cities.append(City("Almaty", "g", "2"))
game.all_cities.append(City("Jekaterinburg", "g", "2"))

game.all_cities.append(City("Nowosibirsk", "h", "2", True))
game.all_cities.append(City("Irkutsk", "h", "2"))
game.all_cities.append(City("UlanBator", "h", "2"))
game.all_cities.append(City("Urumqi", "h", "2"))

game.all_cities.append(City("Wladiwostok", "j", "2"))

game.all_cities.append(City("Magadan", "k", "2"))
game.all_cities.append(City("Sapporo", "k", "2"))
game.all_cities.append(City("PetropawlowskKamtschatskij", "k", "2"))

game.all_cities.append(City("LosAngeles", "a", "3"))

game.all_cities.append(City("ElPaso", "b", "3"))
game.all_cities.append(City("NewOrleans", "b", "3"))
game.all_cities.append(City("Houston", "b", "3"))
game.all_cities.append(City("Jacksonville", "b", "3"))
game.all_cities.append(City("Miami", "b", "3"))
game.all_cities.append(City("Havanna", "b", "3"))
game.all_cities.append(City("Kingston", "b", "3"))
game.all_cities.append(City("Managua", "b", "3"))
game.all_cities.append(City("Guatemala", "b", "3"))
game.all_cities.append(City("MexikoCity", "b", "3"))

game.all_cities.append(City("SantoDomingo", "c", "3"))

game.all_cities.append(City("Azoren", "d", "3"))
game.all_cities.append(City("Lissabon", "d", "3"))
game.all_cities.append(City("Casablanca", "d", "3"))
game.all_cities.append(City("LasPalmas", "d", "3"))

game.all_cities.append(City("Algier", "e", "3"))
game.all_cities.append(City("Tunis", "e", "3"))
game.all_cities.append(City("Tripolis", "e", "3"))

game.all_cities.append(City("Athen", "f", "3"))
game.all_cities.append(City("Ankara", "f", "3"))
game.all_cities.append(City("Nikosia", "f", "3"))
game.all_cities.append(City("Damaskus", "f", "3"))
game.all_cities.append(City("Bagdad", "f", "3"))
game.all_cities.append(City("Jerusalem", "f", "3"))
game.all_cities.append(City("Kairo", "f", "3"))
game.all_cities.append(City("Djidda", "f", "3"))
game.all_cities.append(City("Kuwait", "f", "3"))

game.all_cities.append(City("Teheran", "g", "3"))
game.all_cities.append(City("Samarkand", "g", "3"))
game.all_cities.append(City("Kabul", "g", "3"))
game.all_cities.append(City("Delhi", "g", "3"))
game.all_cities.append(City("Karachi", "g", "3"))
game.all_cities.append(City("Dubai", "g", "3"))
game.all_cities.append(City("Bombay", "g", "3"))

game.all_cities.append(City("Varanasi", "h", "3"))
game.all_cities.append(City("Kalkutta", "h", "3"))
game.all_cities.append(City("Hanoi", "h", "3"))
game.all_cities.append(City("Chongqing", "h", "3"))
game.all_cities.append(City("Lhasa", "h", "3"))

game.all_cities.append(City("Peking", "j", "3"))
game.all_cities.append(City("Xian", "j", "3"))
game.all_cities.append(City("Wuhan", "j", "3"))
game.all_cities.append(City("Shanghai", "j", "3"))
game.all_cities.append(City("Hongkong", "j", "3", True))
game.all_cities.append(City("Taipeh", "j", "3"))
game.all_cities.append(City("Seoul", "j", "3"))
game.all_cities.append(City("Hiroshima", "j", "3"))

game.all_cities.append(City("Tokio", "k", "3"))

game.all_cities.append(City("GalapagosInseln", "b", "4"))
game.all_cities.append(City("Panama", "b", "4"))
game.all_cities.append(City("Bogota", "b", "4"))
game.all_cities.append(City("Quito", "b", "4", True))
game.all_cities.append(City("Lima", "b", "4"))

game.all_cities.append(City("Caracas", "c", "4"))
game.all_cities.append(City("Paramaribo", "c", "4"))
game.all_cities.append(City("Manaus", "c", "4"))

game.all_cities.append(City("Recife", "d", "4"))
game.all_cities.append(City("Dakar", "d", "4"))
game.all_cities.append(City("Monrovia", "d", "4"))

game.all_cities.append(City("Bamako", "e", "4"))
game.all_cities.append(City("Niamey", "e", "4"))
game.all_cities.append(City("NDjamena", "e", "4", True))
game.all_cities.append(City("Abidjan", "e", "4"))
game.all_cities.append(City("Lagos", "e", "4"))
game.all_cities.append(City("Douala", "e", "4"))
game.all_cities.append(City("Kinshasa", "e", "4"))

game.all_cities.append(City("Khartum", "f", "4"))
game.all_cities.append(City("AddisAbeba", "f", "4"))
game.all_cities.append(City("Aden", "f", "4"))
game.all_cities.append(City("Mogadischu", "f", "4"))
game.all_cities.append(City("Nairobi", "f", "4"))
game.all_cities.append(City("DaresSalaam", "f", "4"))

game.all_cities.append(City("Madras", "h", "4"))
game.all_cities.append(City("Colombo", "h", "4"))
game.all_cities.append(City("Rangun", "h", "4"))
game.all_cities.append(City("Bangkok", "h", "4"))
game.all_cities.append(City("HoChiMinhStadt", "h", "4"))
game.all_cities.append(City("Singapur", "h", "4"))
game.all_cities.append(City("Jakarta", "h", "4"))

game.all_cities.append(City("Manila", "j", "4"))

game.all_cities.append(City("Guam", "k", "4"))

game.all_cities.append(City("Osterinsel", "a", "5"))

game.all_cities.append(City("Santiago", "b", "5"))

game.all_cities.append(City("LaPaz", "c", "5"))
game.all_cities.append(City("Brasilia", "c", "5"))
game.all_cities.append(City("Asuncion", "c", "5"))
game.all_cities.append(City("BuenosAires", "c", "5"))
game.all_cities.append(City("SaoPaulo", "c", "5"))
game.all_cities.append(City("RioDeJaneiro", "c", "5"))

game.all_cities.append(City("Luanda", "e", "5"))

game.all_cities.append(City("Windhuk", "f", "5"))
game.all_cities.append(City("Lusaka", "f", "5"))
game.all_cities.append(City("Harare", "f", "5"))
game.all_cities.append(City("Johannesburg", "f", "5"))
game.all_cities.append(City("Maputo", "f", "5"))
game.all_cities.append(City("Antananarivo", "f", "5"))

game.all_cities.append(City("Denpasar", "j", "5"))
game.all_cities.append(City("Darwin", "j", "5"))
game.all_cities.append(City("Perth", "j", "5"))
game.all_cities.append(City("AliceSprings", "j", "5"))

game.all_cities.append(City("PortMoresby", "k", "5"))
game.all_cities.append(City("Brisbane", "k", "5"))
game.all_cities.append(City("Sydney", "k", "5", True))

game.all_cities.append(City("SanCarlosDeBariloche", "b", "6"))
game.all_cities.append(City("PuntaArenas", "b", "6"))

game.all_cities.append(City("Kapstadt", "f", "6"))

game.all_cities.append(City("Adelaide", "j", "6"))
game.all_cities.append(City("Melbourne", "j", "6"))

game.all_cities.append(City("Canberra", "k", "6"))
game.all_cities.append(City("Wellington", "k", "6"))

# create connections

# start connections in A, B, C
game.add_connection(["fairbanks", "inuvik"])
game.add_connection(["inuvik", "churchill"])
game.add_connection(["fairbanks", "juneau"])
game.add_connection(["juneau", "edmonton"])
game.add_connection(["juneau", "vancouver"])
game.add_connection(["juneau", "petropawlowskkamtschatskij"], True)
game.add_connection(["vancouver", "edmonton"])
game.add_connection(["vancouver", "portland"])
game.add_connection(["portland", "sanfrancisco"])
game.add_connection(["portland", "saltlakecity"])
game.add_connection(["sanfrancisco", "saltlakecity"])
game.add_connection(["sanfrancisco", "losangeles"])
game.add_connection(["losangeles", "saltlakecity"])
game.add_connection(["losangeles", "osterinsel"], True)
game.add_connection(["losangeles", "mexikocity"])
game.add_connection(["mexikocity", "elpaso"])
game.add_connection(["mexikocity", "houston"])
game.add_connection(["mexikocity", "havanna"])
game.add_connection(["mexikocity", "guatemala"])
game.add_connection(["elpaso", "houston"])
game.add_connection(["elpaso", "saltlakecity"])
game.add_connection(["elpaso", "winnipeg"])
game.add_connection(["saltlakecity", "winnipeg"])
game.add_connection(["edmonton", "winnipeg"])
game.add_connection(["churchill", "winnipeg"])
game.add_connection(["winnipeg", "chicago"])
game.add_connection(["winnipeg", "montreal"])
game.add_connection(["churchill", "montreal"])
game.add_connection(["chicago", "stlouis"])
game.add_connection(["chicago", "toronto"])
game.add_connection(["stlouis", "newyork"])
game.add_connection(["stlouis", "washington"])
game.add_connection(["stlouis", "neworleans"])
game.add_connection(["neworleans", "houston"])
game.add_connection(["neworleans", "jacksonville"])
game.add_connection(["jacksonville", "miami"])
game.add_connection(["miami", "neworleans"])
game.add_connection(["jacksonville", "washington"])
game.add_connection(["washington", "newyork"])
game.add_connection(["montreal", "newyork"])
game.add_connection(["montreal", "toronto"])
game.add_connection(["mexikocity", "galapagosinseln"])
game.add_connection(["miami", "havanna"])
game.add_connection(["havanna", "kingston"])
game.add_connection(["guatemala", "kingston"])
game.add_connection(["guatemala", "managua"])
game.add_connection(["managua", "kingston"])
game.add_connection(["kingston", "santodomingo"])
game.add_connection(["panama", "managua"])
game.add_connection(["panama", "santodomingo"])
game.add_connection(["panama", "galapagosinseln"])
game.add_connection(["panama", "caracas"])
game.add_connection(["panama", "bogota"])
game.add_connection(["caracas", "bogota"])
game.add_connection(["quito", "bogota"])
game.add_connection(["quito", "lima"])
game.add_connection(["quito", "manaus"])
game.add_connection(["lima", "manaus"])
game.add_connection(["manaus", "paramaribo"])
game.add_connection(["bogota", "paramaribo"])
game.add_connection(["caracas", "paramaribo"])
game.add_connection(["manaus", "lapaz"])
game.add_connection(["lima", "lapaz"])
game.add_connection(["lapaz", "asuncion"])
game.add_connection(["lapaz", "riodejaneiro"])
game.add_connection(["lapaz", "santiago"])
game.add_connection(["asuncion", "buenosaires"])
game.add_connection(["asuncion", "brasilia"])
game.add_connection(["manaus", "brasilia"])
game.add_connection(["santiago", "sancarlosdebariloche"])
game.add_connection(["santiago", "buenosaires"])
game.add_connection(["lapaz", "osterinsel"], True)
game.add_connection(["santiago", "osterinsel"], True)
game.add_connection(["galapagosinseln", "osterinsel"])
game.add_connection(["galapagosinseln", "lima"])
game.add_connection(["osterinsel", "wellington"], True)
game.add_connection(["sancarlosdebariloche", "buenosaires"])
game.add_connection(["puntaarenas", "sancarlosdebariloche"])
game.add_connection(["puntaarenas", "buenosaires"])
game.add_connection(["brasilia", "riodejaneiro"])
game.add_connection(["brasilia", "recife"])
game.add_connection(["manaus", "recife"])
game.add_connection(["brasilia", "saopaulo"])
game.add_connection(["riodejaneiro", "saopaulo"])
game.add_connection(["newyork", "stjohns"])
game.add_connection(["montreal", "stjohns"])
game.add_connection(["montreal", "nuuk"])
game.add_connection(["stjohns", "nuuk"])
game.add_connection(["nuuk", "reykjavik"])
# end connections in A, B, C

# begin connections D, E, F
game.add_connection(["montreal", "dublin"], True)
game.add_connection(["newyork", "london"], True)
game.add_connection(["madrid", "jacksonville"], True)
game.add_connection(["santodomingo", "azoren"], True)
game.add_connection(["caracas", "laspalmas"], True)
game.add_connection(["paramaribo", "monrovia"], True)
game.add_connection(["recife", "kinshasa"], True)
game.add_connection(["riodejaneiro", "kapstadt"], True)
game.add_connection(["buenosaires", "kapstadt"], True)
game.add_connection(["barentsburg", "reykjavik"])
game.add_connection(["reykjavik", "oslo"])
game.add_connection(["reykjavik", "dublin"])
game.add_connection(["dublin", "london"])
game.add_connection(["dublin", "lissabon"])
game.add_connection(["lissabon", "madrid"])
game.add_connection(["lissabon", "casablanca"])
game.add_connection(["madrid", "casablanca"])
game.add_connection(["madrid", "laspalmas"])
game.add_connection(["casablanca", "laspalmas"])
game.add_connection(["london", "brussel"])
game.add_connection(["london", "paris"])
game.add_connection(["brussel", "paris"])
game.add_connection(["brussel", "amsterdam"])
game.add_connection(["amsterdam", "kopenhagen"])
game.add_connection(["kopenhagen", "brussel"])
game.add_connection(["brussel", "prag"])
game.add_connection(["brussel", "wien"])
game.add_connection(["paris", "bern"])
game.add_connection(["bern", "rom"])
game.add_connection(["bern", "berlin"])
game.add_connection(["paris", "madrid"])
game.add_connection(["madrid", "rom"])
game.add_connection(["azoren", "lissabon"])
game.add_connection(["azoren", "laspalmas"])
game.add_connection(["wien", "prag"])
game.add_connection(["berlin", "prag"])
game.add_connection(["wien", "warschau"])
game.add_connection(["wien", "budapest"])
game.add_connection(["wien", "rom"])
game.add_connection(["rom", "budapest"])
game.add_connection(["budapest", "belgrad"])
game.add_connection(["belgrad", "sofia"])
game.add_connection(["rom", "athen"])
game.add_connection(["rom", "tunis"])
game.add_connection(["berlin", "riga"])
game.add_connection(["berlin", "kopenhagen"])
game.add_connection(["berlin", "stockholm"])
game.add_connection(["oslo", "stockholm"])
game.add_connection(["oslo", "trondheim"])
game.add_connection(["barentsburg", "trondheim"])
game.add_connection(["barentsburg", "murmansk"])
game.add_connection(["trondheim", "murmansk"])
game.add_connection(["trondheim", "helsinki"])
game.add_connection(["helsinki", "murmansk"])
game.add_connection(["stockholm", "helsinki"])
game.add_connection(["helsinki", "stpetersburg"])
game.add_connection(["murmansk", "stpetersburg"])
game.add_connection(["stpetersburg", "riga"])
game.add_connection(["sofia", "bukarest"])
game.add_connection(["casablanca", "algier"])
game.add_connection(["algier", "tunis"])
game.add_connection(["tunis", "tripolis"])
game.add_connection(["laspalmas", "tripolis"])
game.add_connection(["laspalmas", "dakar"])
game.add_connection(["dakar", "kairo"])
game.add_connection(["tripolis", "kairo"])
game.add_connection(["algier", "niamey"])
game.add_connection(["dakar", "bamako"])
game.add_connection(["dakar", "monrovia"])
game.add_connection(["monrovia", "abidjan"])
game.add_connection(["monrovia", "bamako"])
game.add_connection(["abidjan", "niamey"])
game.add_connection(["bamako", "niamey"])
game.add_connection(["abidjan", "lagos"])
game.add_connection(["niamey", "lagos"])
game.add_connection(["niamey", "ndjamena"])
game.add_connection(["lagos", "douala"])
game.add_connection(["douala", "ndjamena"])
game.add_connection(["ndjamena", "kairo"])
game.add_connection(["ndjamena", "khartum"])
game.add_connection(["douala", "kinshasa"])
game.add_connection(["kinshasa", "khartum"])
game.add_connection(["kinshasa", "luanda"])
game.add_connection(["luanda", "windhuk"])
game.add_connection(["windhuk", "kapstadt"])
game.add_connection(["kapstadt", "johannesburg"])
game.add_connection(["johannesburg", "maputo"])
game.add_connection(["windhuk", "johannesburg"])
game.add_connection(["maputo", "harare"])
game.add_connection(["maputo", "antananarivo"])
game.add_connection(["antananarivo", "daressalaam"])
game.add_connection(["antananarivo", "mogadischu"])
game.add_connection(["harare", "lusaka"])
game.add_connection(["lusaka", "windhuk"])
game.add_connection(["kinshasa", "lusaka"])
game.add_connection(["lusaka", "nairobi"])
game.add_connection(["harare", "daressalaam"])
game.add_connection(["daressalaam", "mogadischu"])
game.add_connection(["nairobi", "mogadischu"])
game.add_connection(["mogadischu", "addisabeba"])
game.add_connection(["addisabeba", "khartum"])
game.add_connection(["addisabeba", "aden"])
game.add_connection(["aden", "dubai"])
game.add_connection(["aden", "djidda"])
game.add_connection(["aden", "kuwait"])
game.add_connection(["djidda", "khartum"])
game.add_connection(["khartum", "kairo"])
game.add_connection(["djidda", "kairo"])
game.add_connection(["kairo", "jerusalem"])
game.add_connection(["kairo", "athen"])
game.add_connection(["jerusalem", "damaskus"])
game.add_connection(["damaskus", "nikosia"])
game.add_connection(["nikosia", "bagdad"])
game.add_connection(["nikosia", "ankara"])
game.add_connection(["athen", "nikosia"])
game.add_connection(["athen", "ankara"])
game.add_connection(["sofia", "ankara"])
game.add_connection(["ankara", "tiflis"])
game.add_connection(["bukarest", "wolgograd"])
game.add_connection(["budapest", "kiew"])
game.add_connection(["warschau", "kiew"])
game.add_connection(["berlin", "warschau"])
game.add_connection(["kiew", "moskau"])
game.add_connection(["stpetersburg", "moskau"])
game.add_connection(["moskau", "wolgograd"])
game.add_connection(["murmansk", "archangelsk"])
game.add_connection(["moskau", "archangelsk"])
game.add_connection(["archangelsk", "jekaterinburg"])
game.add_connection(["moskau", "jekaterinburg"])
game.add_connection(["wolgograd", "jekaterinburg"])
game.add_connection(["wolgograd", "almaty"])
game.add_connection(["wolgograd", "tiflis"])
game.add_connection(["tiflis", "baku"])
game.add_connection(["baku", "teheran"])
game.add_connection(["teheran", "kuwait"])
game.add_connection(["norilsk", "murmansk"])
game.add_connection(["archangelsk", "norilsk"])
game.add_connection(["nairobi", "perth"], True)
game.add_connection(["mogadischu", "bangkok"], True)
game.add_connection(["baku", "almaty"])
game.add_connection(["athen", "sofia"])
game.add_connection(["oslo", "kopenhagen"])
game.add_connection(["bagdad", "kuwait"])
game.add_connection(["kuwait", "kabul"])
game.add_connection(["kapstadt", "adelaide"], True)
# end connections D, E, F

# begin connections G, H, J, K
game.add_connection(["jekaterinburg", "norilsk"])
game.add_connection(["jekaterinburg", "nowosibirsk"])
game.add_connection(["norilsk", "nowosibirsk"])
game.add_connection(["norilsk", "jakutsk"])
game.add_connection(["nowosibirsk", "jakutsk"])
game.add_connection(["nowosibirsk", "irkutsk"])
game.add_connection(["almaty", "nowosibirsk"])
game.add_connection(["jakutsk", "magadan"])
game.add_connection(["magadan", "petropawlowskkamtschatskij"])
game.add_connection(["petropawlowskkamtschatskij", "sapporo"])
game.add_connection(["sapporo", "tokio"])
game.add_connection(["sapporo", "wladiwostok"])
game.add_connection(["magadan", "wladiwostok"])
game.add_connection(["tokio", "hiroshima"])
game.add_connection(["seoul", "tokio"])
game.add_connection(["seoul", "hiroshima"])
game.add_connection(["seoul", "wladiwostok"])
game.add_connection(["seoul", "shanghai"])
game.add_connection(["shanghai", "taipeh"])
game.add_connection(["shanghai", "peking"])
game.add_connection(["taipeh", "guam"])
game.add_connection(["guam", "manila"])
game.add_connection(["manila", "hongkong"])
game.add_connection(["manila", "hochiminhstadt"])
game.add_connection(["hochiminhstadt", "hanoi"])
game.add_connection(["hanoi", "hongkong"])
game.add_connection(["taipeh", "hongkong"])
game.add_connection(["hanoi", "peking"])
game.add_connection(["hongkong", "bangkok"])
game.add_connection(["peking", "wuhan"])
game.add_connection(["peking", "wladiwostok"])
game.add_connection(["peking", "xian"])
game.add_connection(["xian", "chongqing"])
game.add_connection(["peking", "lhasa"])
game.add_connection(["peking", "ulanbator"])
game.add_connection(["peking", "delhi"])
game.add_connection(["irkutsk", "ulanbator"])
game.add_connection(["magadan", "irkutsk"])
game.add_connection(["peking", "magadan"])
game.add_connection(["ulanbator", "almaty"])
game.add_connection(["ulanbator", "urumqi"])
game.add_connection(["samarkand", "urumqi"])
game.add_connection(["almaty", "samarkand"])
game.add_connection(["samarkand", "kabul"])
game.add_connection(["kabul", "teheran"])
game.add_connection(["dubai", "kabul"])
game.add_connection(["dubai", "karachi"])
game.add_connection(["kabul", "delhi"])
game.add_connection(["karachi", "delhi"])
game.add_connection(["samarkand", "delhi"])
game.add_connection(["karachi", "bombay"])
game.add_connection(["bombay", "delhi"])
game.add_connection(["bombay", "colombo"])
game.add_connection(["colombo", "delhi"])
game.add_connection(["colombo", "madras"])
game.add_connection(["madras", "delhi"])
game.add_connection(["madras", "kalkutta"])
game.add_connection(["kalkutta", "varanasi"])
game.add_connection(["varanasi", "delhi"])
game.add_connection(["delhi", "lhasa"])
game.add_connection(["kalkutta", "lhasa"])
game.add_connection(["lhasa", "chongqing"])
game.add_connection(["chongqing", "wuhan"])
game.add_connection((["wuhan", "shanghai"]))
game.add_connection(["kalkutta", "rangun"])
game.add_connection(["colombo", "rangun"])
game.add_connection(["rangun", "bangkok"])
game.add_connection(["bangkok", "singapur"])
game.add_connection(["singapur", "jakarta"])
game.add_connection(["jakarta", "denpasar"])
game.add_connection(["denpasar", "darwin"])
game.add_connection(["darwin", "portmoresby"])
game.add_connection(["portmoresby", "brisbane"])
game.add_connection(["portmoresby", "sydney"])
game.add_connection(["brisbane", "sydney"])
game.add_connection(["sydney", "wellington"])
game.add_connection(["wellington", "melbourne"])
game.add_connection(["melbourne", "canberra"])
game.add_connection(["canberra", "sydney"])
game.add_connection(["melbourne", "sydney"])
game.add_connection(["sydney", "adelaide"])
game.add_connection(["sydney", "perth"])
game.add_connection(["sydney", "alicesprings"])
game.add_connection(["alicesprings", "darwin"])
game.add_connection(["alicesprings", "perth"])
game.add_connection(["perth", "darwin"])
# end connections G, H, J, K

print("Done setup")

if __name__ == "__main__":

    # results = game.get_city_by_name("LosAngeles").get_adjacent_cities()
    #
    # all_reachable = True
    # for city in game.all_cities:
    #     print(city.name)
    #     result = city.get_possible_destinations(12)
    #     all_reachable &= len(result) == 173
    #     if not all_reachable:
    #         break
    # print(all_reachable)
    #
    # la = game.get_city_by_name("LosAngeles")
    # sf = game.get_city_by_name("SanFrancisco")
    # slc = game.get_city_by_name("Saltlakecity")
    # mc = game.get_city_by_name("MexikoCity")
    # ep = game.get_city_by_name("ElPaso")
    # p1 = Path([la, sf, la])  # not valid
    # p2 = Path([la, sf, slc, la])  # valid
    # p3 = Path([sf, la, mc, ep, slc])  # valid
    # p4 = Path([sf, la, mc, la, slc])  # not valid
    # print(p1.is_valid())
    # print(p2.is_valid())
    # print(p3.is_valid())
    # print(p4.is_valid())

    # game.check_conn_number()

    print(game.estimate_city_dist(game.get_city_by_name("Fairbanks"), game.get_city_by_name("Wellington")))


    print("Test concluded")

